version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  - greet:
      executor:
        name: win/default # executor type
        size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
      steps:
        - checkout
        - run:
            command: echo "Hello welcome"
  - test2: # another custom job; runs test suite 2,
      requires: # test2 is dependent on the success of job `greet`
        - greet
  - hold: # <<< A job that will require manual approval in the CircleCI web application.
      type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
      requires: # We only run the "hold" job when test2 has succeeded
        - test2
workflows:
  manual:
    jobs:
      - greet
      - test2
