version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  hold:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified 
    steps:
      - run: echo "in hold"
  deploy:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      - run: echo "in deploy"
workflows:
  customTrigger:
    jobs:
      - hold:
          requires:
          type: approval
      - deploy:
          requires:
            - hold