version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

workflows:
  manual:
    jobs:
      - greet:
          type: approval
      - msg:
          requires: 
            - greet
          steps:
            - checkout
            - run:
                command: echo "Hello welcome"
      