version: 2 

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  greet: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      - run: echo 'Hello, Windows'
  hold:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified 
    steps:
      - run: echo "in hold"
  deploy:
    steps:
      - run: echo "bye"
workflows:
  version: 2
  customTrigger:
    jobs:
      - greet
      - hold:
          type: approval
          requires:
            - greet
      - deploy
          requires:
            - hold