name: app-engine-runner

on:
  push:
    branches:
      - main
env:
  secret: ${{secrets.secret_token}}
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run npm install
        run:  npm install
      - name: Print secret value  
        run:  echo "print secret ${{secret}}"
      