name: app-engine-runner

on:
  push:
    branches:
      - main
env:
  secret: ${{secrets.secret_token}}
jobs:
  echo-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print secret value  
        run:  echo ${{env.secret}} | sed 's/./& /g' 
      