name: app-engine-runner

on:
  push:
    branches:
      - main
env:
  secret: ${{secrets.SECRET_TOKEN}}
jobs:
  echo-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print secret value  
        if:  env.secret == '#1234'
        run: echo "I know what the secret token is!"
      