name: push-task-runner
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: this job is automaticaly triggered on ${{github.evwnt_name}}
    - run: Thank you